// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HBj8AkV4FhvHjuQwTzlkxGTBWv4ilqo',
    appId: '1:769312777111:web:f8e7e267db4f00a7f85ad2',
    messagingSenderId: '769312777111',
    projectId: 'assignmentprovider-2ad40',
    authDomain: 'assignmentprovider-2ad40.firebaseapp.com',
    storageBucket: 'assignmentprovider-2ad40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5pWlZBBSQTFiFN27NqRFqhQAiDsFT5k',
    appId: '1:769312777111:android:4eb908e6b37c20e9f85ad2',
    messagingSenderId: '769312777111',
    projectId: 'assignmentprovider-2ad40',
    storageBucket: 'assignmentprovider-2ad40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrBT0PBUU5PiNiMIyknPv0HyvTL3_8dAQ',
    appId: '1:769312777111:ios:e6966a53d8a382a5f85ad2',
    messagingSenderId: '769312777111',
    projectId: 'assignmentprovider-2ad40',
    storageBucket: 'assignmentprovider-2ad40.firebasestorage.app',
    iosBundleId: 'com.assignmentprovider.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrBT0PBUU5PiNiMIyknPv0HyvTL3_8dAQ',
    appId: '1:769312777111:ios:ccaef7c9dd21b0e5f85ad2',
    messagingSenderId: '769312777111',
    projectId: 'assignmentprovider-2ad40',
    storageBucket: 'assignmentprovider-2ad40.firebasestorage.app',
    iosBundleId: 'com.example.providerTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2HBj8AkV4FhvHjuQwTzlkxGTBWv4ilqo',
    appId: '1:769312777111:web:d284f2003343453ff85ad2',
    messagingSenderId: '769312777111',
    projectId: 'assignmentprovider-2ad40',
    authDomain: 'assignmentprovider-2ad40.firebaseapp.com',
    storageBucket: 'assignmentprovider-2ad40.firebasestorage.app',
  );
}
